# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /data/home2/qiupingw/Softcore/PAWS_softcore_vc707_vivado2019.srcs/constrs_1/new/const.xdc

# IP: ip/clk_wiz_0/clk_wiz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet
