# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7k325tffg900-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /data/home2/qiupingw/Softcore/PAWS_softcore_ax7325b_vivado2018/PAWS_softcore_ax7325b_vivado2018.cache/wt [current_project]
set_property parent.project_path /data/home2/qiupingw/Softcore/PAWS_softcore_ax7325b_vivado2018/PAWS_softcore_ax7325b_vivado2018.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /data/home2/qiupingw/Softcore/PAWS_softcore_ax7325b_vivado2018/PAWS_softcore_ax7325b_vivado2018.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog /data/home2/qiupingw/Softcore/PAWS_softcore_vc707_vivado2019.srcs/sources_1/imports/RTL_wsl_version/wasm_defines.vh
read_verilog -library xil_defaultlib {
  /data/home2/qiupingw/Softcore/PAWS_softcore_vc707_vivado2019.srcs/sources_1/imports/RTL_wsl_version/ALU.v
  /data/home2/qiupingw/Softcore/PAWS_softcore_vc707_vivado2019.srcs/sources_1/imports/RTL_wsl_version/ALU_32bit.v
  /data/home2/qiupingw/Softcore/PAWS_softcore_vc707_vivado2019.srcs/sources_1/imports/RTL_wsl_version/ControlStack.v
  /data/home2/qiupingw/Softcore/PAWS_softcore_vc707_vivado2019.srcs/sources_1/imports/RTL_wsl_version/CtrlUnit.v
  /data/home2/qiupingw/Softcore/PAWS_softcore_vc707_vivado2019.srcs/sources_1/imports/RTL_wsl_version/InstrMemCtrl.v
  /data/home2/qiupingw/Softcore/PAWS_softcore_vc707_vivado2019.srcs/sources_1/imports/RTL_wsl_version/LEB128_uint_decode_64bit.v
  /data/home2/qiupingw/Softcore/PAWS_softcore_vc707_vivado2019.srcs/sources_1/imports/RTL_wsl_version/LineMemory.v
  /data/home2/qiupingw/Softcore/PAWS_softcore_vc707_vivado2019.srcs/sources_1/imports/RTL_wsl_version/OperandStack.v
  /data/home2/qiupingw/Softcore/PAWS_softcore_vc707_vivado2019.srcs/sources_1/new/UART.v
  /data/home2/qiupingw/Softcore/PAWS_softcore_vc707_vivado2019.srcs/sources_1/new/UART_Rx.v
  /data/home2/qiupingw/Softcore/PAWS_softcore_vc707_vivado2019.srcs/sources_1/new/UART_Tx.v
  /data/home2/qiupingw/Softcore/PAWS_softcore_vc707_vivado2019.srcs/sources_1/imports/RTL_wsl_version/WASM_TOP.v
  /data/home2/qiupingw/Softcore/PAWS_softcore_vc707_vivado2019.srcs/sources_1/new/blk_mem.v
  /data/home2/qiupingw/Softcore/PAWS_softcore_vc707_vivado2019.srcs/sources_1/imports/new/uart_rx_instr.v
  /data/home2/qiupingw/Softcore/PAWS_softcore_vc707_vivado2019.srcs/sources_1/new/softcore_top.v
}
read_ip -quiet /data/home2/qiupingw/Softcore/PAWS_softcore_ax7325b_vivado2018/PAWS_softcore_ax7325b_vivado2018.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all /data/home2/qiupingw/Softcore/PAWS_softcore_ax7325b_vivado2018/PAWS_softcore_ax7325b_vivado2018.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all /data/home2/qiupingw/Softcore/PAWS_softcore_ax7325b_vivado2018/PAWS_softcore_ax7325b_vivado2018.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all /data/home2/qiupingw/Softcore/PAWS_softcore_ax7325b_vivado2018/PAWS_softcore_ax7325b_vivado2018.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

read_ip -quiet /data/home2/qiupingw/Softcore/PAWS_softcore_ax7325b_vivado2018/PAWS_softcore_ax7325b_vivado2018.srcs/sources_1/ip/ila_0/ila_0.xci
set_property used_in_synthesis false [get_files -all /data/home2/qiupingw/Softcore/PAWS_softcore_ax7325b_vivado2018/PAWS_softcore_ax7325b_vivado2018.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /data/home2/qiupingw/Softcore/PAWS_softcore_ax7325b_vivado2018/PAWS_softcore_ax7325b_vivado2018.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /data/home2/qiupingw/Softcore/PAWS_softcore_ax7325b_vivado2018/PAWS_softcore_ax7325b_vivado2018.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all /data/home2/qiupingw/Softcore/PAWS_softcore_ax7325b_vivado2018/PAWS_softcore_ax7325b_vivado2018.srcs/sources_1/ip/ila_0/ila_0_ooc.xdc]

read_ip -quiet /data/home2/qiupingw/Softcore/PAWS_softcore_ax7325b_vivado2018/PAWS_softcore_ax7325b_vivado2018.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all /data/home2/qiupingw/Softcore/PAWS_softcore_ax7325b_vivado2018/PAWS_softcore_ax7325b_vivado2018.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /data/home2/qiupingw/Softcore/PAWS_softcore_vc707_vivado2019.srcs/constrs_1/new/const.xdc
set_property used_in_implementation false [get_files /data/home2/qiupingw/Softcore/PAWS_softcore_vc707_vivado2019.srcs/constrs_1/new/const.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top softcore_top -part xc7k325tffg900-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef softcore_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file softcore_top_utilization_synth.rpt -pb softcore_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
